In [ ]:
                                                         # ------ NUMPY ------- #

In [3]:
#Creating NumPy Arrays
# From lists
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Built-in functions
zeros = np.zeros((3, 4))      # 3x4 array of zeros
ones = np.ones((2, 3))         # 2x3 array of ones
empty = np.empty((2, 2))       # Uninitialized array
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced numbers from 0 to 1
identity = np.eye(3)            # 3x3 identity matrix
random_arr = np.random.rand(3, 3)  # Random numbers between 0-1

In [4]:
#Array Attributes
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(f"Shape: {arr.shape}")      
print(f"Dimensions: {arr.ndim}")   
print(f"Size: {arr.size}")        
print(f"Data type: {arr.dtype}")   
print(f"Item size: {arr.itemsize} bytes")  
print(f"Total bytes: {arr.nbytes}")  

Shape: (2, 4)
Dimensions: 2
Size: 8
Data type: int64
Item size: 8 bytes
Total bytes: 64


In [5]:
#Array Indexing and Slicing
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Basic indexing
print(arr[0, 1])        # First row, second element: 2
print(arr[1])           # Second row: [5, 6, 7, 8]

# Slicing
print(arr[:, 1])        # All rows, second column: [2, 6, 10]
print(arr[0:2, 1:3])    # Rows 0-1, columns 1-2
print(arr[::-1])        # Reverse rows

# Boolean indexing
print(arr[arr > 5])     # Elements greater than 5

2
[5 6 7 8]
[ 2  6 10]
[[2 3]
 [6 7]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[ 6  7  8  9 10 11 12]


In [6]:
#Array Operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Arithmetic operations
print(a + b)      # [6, 8, 10, 12]
print(a * b)      # [5, 12, 21, 32]
print(a ** 2)     # [1, 4, 9, 16]
print(np.sqrt(a)) # [1, 1.41, 1.73, 2]

# Universal functions (ufuncs)
print(np.sin(a))  # Trigonometric functions
print(np.exp(a))  # Exponential
print(np.log(a))  # Natural log

[ 6  8 10 12]
[ 5 12 21 32]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [7]:
#Broadcasting
# NumPy can perform operations on arrays of different shapes
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

print(arr + scalar)  # Add scalar to every element


# Broadcasting with different dimensions
row = np.array([1, 2, 3])
print(arr + row)  # Add row to each row of arr


[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


In [8]:
#Aggregation Functions
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"Sum: {np.sum(arr)}")              
print(f"Mean: {np.mean(arr)}")             
print(f"Std deviation: {np.std(arr)}")    
print(f"Min: {np.min(arr)}")               
print(f"Max: {np.max(arr)}")               

# Axis-wise operations
print(f"Sum across rows: {np.sum(arr, axis=0)}") 
print(f"Sum across columns: {np.sum(arr, axis=1)}")  

# Cumulative operations
print(f"Cumulative sum: {np.cumsum(arr)}")

Sum: 45
Mean: 5.0
Std deviation: 2.581988897471611
Min: 1
Max: 9
Sum across rows: [12 15 18]
Sum across columns: [ 6 15 24]
Cumulative sum: [ 1  3  6 10 15 21 28 36 45]


In [9]:
#Reshaping and Manipulation
arr = np.arange(12)
print(arr)
# Reshape
reshaped = arr.reshape(3, 4)
print(reshaped)

# Flatten
flattened = reshaped.flatten()  # Returns copy
raveled = reshaped.ravel()       # Returns view

# Stacking
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))  # Vertical stack
print(np.hstack((a, b)))  # Horizontal stack

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [10]:
#Linear Algebra Operations
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication
print(A @ B)         # Same as above (Python 3.5+)

# Other linear algebra functions
print(np.linalg.inv(A))      # Inverse
print(np.linalg.det(A))      # Determinant
print(np.linalg.eig(A))      # Eigenvalues and eigenvectors

# Solving linear equations
# Solve: 3x + y = 9, x + 2y = 8
coefficients = np.array([[3, 1], [1, 2]])
constants = np.array([9, 8])
solution = np.linalg.solve(coefficients, constants)
print(solution)  # [2, 3]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[2. 3.]


In [11]:
#Practical Examples
#Data Normalization
def normalize_data(data):
    """Normalize data to have mean 0 and std 1"""
    return (data - np.mean(data)) / np.std(data)

data = np.random.randn(10) * 10 + 5  # Generate random data of 1000 data points
print(data)
print("****************************************************************************************************************************************")
normalized = normalize_data(data)
print(f"After normalization - Mean: {np.mean(normalized):.2f}, Std: {np.std(normalized):.2f}")


[16.32185445 -2.58736024 21.3351042  14.95248853 17.16037844 27.61856041
  5.57774124  9.59936364 14.01215377 -0.92297675]
****************************************************************************************************************************************
After normalization - Mean: 0.00, Std: 1.00


In [12]:
#Basic array Creation: Create the following arrays:
#A 1D array of numbers from 10 to 50 (inclusive)
#A 2D array of shape (3,4) filled with random integers between 1 and 100
#A 3x3 identity matrix
#An array of 10 evenly spaced numbers between 0 and 2π

import numpy as np
arr1 = np.arange(10, 51)
print(f"1. {arr1}")


arr2 = np.random.randint(1, 101, size=(3, 4))
print(f"2.\n{arr2}")


arr3 = np.eye(3)
print(f"3.\n{arr3}")


arr4 = np.linspace(0, 2*np.pi, 10)
print(f"4. {arr4}")



1. [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
2.
[[ 1 84 52  8]
 [ 7 40 97 43]
 [72 97 89 62]]
3.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. [0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [13]:
# Array Manipulation: Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), perform:
# Extract the second row
# Extract the element in the third row, first column
# Extract all elements greater than 5
# Replace all even numbers with 0
# Calculate the mean of each column

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Second row: ",arr[1,:])
print(f"\nElement in the third row, first column: {arr[2][0]}")
print(f"\nElements greater than 5: {arr[arr>5]}")

arr_copy = arr.copy()
arr_copy[arr_copy % 2 == 0] = 0
print(f"\nAfter replacing evens:\n{arr_copy}")
print(f"\nMean: {np.mean(arr,axis=0)}")


Second row:  [4 5 6]

Element in the third row, first column: 7

Elements greater than 5: [6 7 8 9]

After replacing evens:
[[1 0 3]
 [0 5 0]
 [7 0 9]]

Mean: [4. 5. 6.]


In [17]:
# Mathematical Operations: Create two arrays A = np.array([[1, 2], [3, 4]]) and B = np.array([[5, 6], [7, 8]]). Calculate:
# Element-wise multiplication
# Matrix multiplication
# Determinant of A
# Inverse of A
# Eigenvalues of A

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f"Element-wise multiplication: {A*B}")
print(f"\nMatrix multiplication: {A@B}")
print(f"\nDeterminant of A: {np.linalg.det(A):.2f}")
print(f"\nInverse of A: {np.linalg.inv(A)}")
print(f"\nEigenvalues of A: {np.linalg.eigvals(A)}")


Element-wise multiplication: [[ 5 12]
 [21 32]]

Matrix multiplication: [[19 22]
 [43 50]]

Determinant of A: -2.00

Inverse of A: [[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues of A: [-0.37228132  5.37228132]


In [16]:
# Broadcasting: Without using loops, perform:
# Subtract the mean of each column from its respective column in a 2D array
# Create a 5x5 array with row values ranging from 0 to 4
# Normalize each row of a 2D array to sum to 1
# Add a 1D array of length 3 to each row of a 4x3 array

# 1. Subtract column means
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
col_means = np.mean(data, axis=0)
centered_data = data - col_means
print(f"Centered data:\n{centered_data}")

# 2. 5x5 with row values 0-4
rows = np.arange(5)
grid = np.tile(rows, (5, 1))
print(f"\nGrid:\n{grid}")

# 3. Normalize rows to sum to 1
arr = np.random.randint(1, 10, size=(4, 3))
row_sums = np.sum(arr, axis=1, keepdims=True)
normalized = arr / row_sums
print(f"\nOriginal:\n{arr}")
print(f"\nRow sums: {np.sum(arr, axis=1)}")
print(f"\nNormalized:\n{normalized}")
print(f"\nNew row sums: {np.sum(normalized, axis=1)}")

# 4. Add 1D array to each row
matrix_4x3 = np.arange(12).reshape(4, 3)
vector = np.array([10, 20, 30])
result = matrix_4x3 + vector
print(f"\nMatrix:\n{matrix_4x3}")
print(f"\nVector: {vector}")
print(f"\nResult:\n{result}")


Centered data:
[[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]

Grid:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

Original:
[[1 7 4]
 [7 6 2]
 [6 2 1]
 [9 4 6]]

Row sums: [12 15  9 19]

Normalized:
[[0.08333333 0.58333333 0.33333333]
 [0.46666667 0.4        0.13333333]
 [0.66666667 0.22222222 0.11111111]
 [0.47368421 0.21052632 0.31578947]]

New row sums: [1. 1. 1. 1.]

Matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Vector: [10 20 30]

Result:
[[10 21 32]
 [13 24 35]
 [16 27 38]
 [19 30 41]]


In [15]:
# Data Analysis: You have temperature data for a week (7 days) from 3 different cities:

# Data: rows = cities, columns = days (Mon-Sun)
# temperatures = np.array([
#     [20, 22, 21, 23, 24, 22, 21],  # City A
#    [15, 16, 15, 17, 18, 16, 15],  # City B
#    [25, 26, 24, 27, 28, 26, 25]   # City C
#])
# Calculate:
# 1. The average temperature for each city
# 2. The hottest day across all cities (which day of week)
# 3. The city with the highest temperature variation
# 4. The number of days where City A was warmer than City B
# 5. Normalize the temperatures for each city to range [0, 1]

temperatures = np.array([
    [20, 22, 21, 23, 24, 22, 21],
    [15, 16, 15, 17, 18, 16, 15],
    [25, 26, 24, 27, 28, 26, 25]
])

days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

# 1. Average for each city
city_avg = np.mean(temperatures, axis=1)
for i, avg in enumerate(city_avg):
    print(f"City {chr(65+i)} average: {avg:.2f}°C")

#2. Hottest day overall
max_temp_idx = np.argmax(temperatures)
city_idx, day_idx = np.unravel_index(max_temp_idx, temperatures.shape)
print(f"\nHottest day: {days[day_idx]} in City {chr(65+city_idx)} at {temperatures[city_idx, day_idx]}°C")

# 3. City with highest variation (standard deviation)
city_std = np.std(temperatures, axis=1)
highest_var_city = np.argmax(city_std)
print(f"\nCity with highest variation: City {chr(65+highest_var_city)} (std: {city_std[highest_var_city]:.2f})")

# 4. Days where City A > City B
warmer_days = np.sum(temperatures[0] > temperatures[1])
print(f"\nCity A was warmer than City B on {warmer_days} days")

# 5. Normalize each city's temperatures to [0, 1]
city_min = np.min(temperatures, axis=1, keepdims=True)
city_max = np.max(temperatures, axis=1, keepdims=True)
normalized_temps = (temperatures - city_min) / (city_max - city_min)
print(f"Normalized temperatures:\n{normalized_temps}")


City A average: 21.86°C
City B average: 16.00°C
City C average: 25.86°C

Hottest day: Fri in City C at 28°C

City with highest variation: City A (std: 1.25)

City A was warmer than City B on 7 days
Normalized temperatures:
[[0.         0.5        0.25       0.75       1.         0.5
  0.25      ]
 [0.         0.33333333 0.         0.66666667 1.         0.33333333
  0.        ]
 [0.25       0.5        0.         0.75       1.         0.5
  0.25      ]]


In [14]:
#Boolean Masking: Given the array scores = np.array([[85, 92, 78], [90, 88, 95], [76, 82, 91], [88, 85, 79]])
#representing test scores (rows = students, columns = subjects), find:tudents who scored above 90 in any subject
#Subjects where average score is above 85
#Create a mask for scores between 80 and 90 (inclusive)
#Replace all scores below 80 with the subject's mean

scores = np.array([[85, 92, 78], [90, 88, 95], [76, 82, 91], [88, 85, 79]])

# 1. Students with any score > 90
any_above_90 = np.any(scores > 90, axis=1)
print(f"Students with any score > 90: {np.where(any_above_90)[0]}")

# 2. Subjects with average > 85
subject_avg = np.mean(scores, axis=0)
high_avg_subjects = np.where(subject_avg > 85)[0]
print(f"\nSubjects with avg > 85: {high_avg_subjects}")

# 3. Mask for scores 80-90
mask_80_90 = (scores >= 80) & (scores <= 90)
print(f"\nMask for scores 80-90:\n{mask_80_90}")

# 4. Replace scores < 80 with subject mean
scores_fixed = scores.copy()
subject_means = np.mean(scores, axis=0)
low_scores_mask = scores < 80
scores_fixed[low_scores_mask] = np.tile(subject_means, (scores.shape[0], 1))[low_scores_mask]
print(f"\nFixed scores:\n{scores_fixed}")


Students with any score > 90: [0 1 2]

Subjects with avg > 85: [1 2]

Mask for scores 80-90:
[[ True False False]
 [ True  True False]
 [False  True False]
 [ True  True False]]

Fixed scores:
[[85 92 85]
 [90 88 95]
 [84 82 91]
 [88 85 85]]
