In [ ]:
                                                        #   ---------NUMPY--------   # 

In [33]:
#Basic array Creation: Create the following arrays:
#A 1D array of numbers from 10 to 50 (inclusive)
#A 2D array of shape (3,4) filled with random integers between 1 and 100
#A 3x3 identity matrix
#An array of 10 evenly spaced numbers between 0 and 2π

import numpy as np
arr1 = np.arange(10, 51)
print(f"1. {arr1}")


arr2 = np.random.randint(1, 101, size=(3, 4))
print(f"2.\n{arr2}")


arr3 = np.eye(3)
print(f"3.\n{arr3}")


arr4 = np.linspace(0, 2*np.pi, 10)
print(f"4. {arr4}")



1. [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
2.
[[12 53 11 38]
 [96 77 90 13]
 [18 39 66 88]]
3.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. [0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [42]:
# Array Manipulation: Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), perform:
# Extract the second row
# Extract the element in the third row, first column
# Extract all elements greater than 5
# Replace all even numbers with 0
# Calculate the mean of each column

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Second row: ",arr[1,:])
print(f"\nElement in the third row, first column: {arr[2][0]}")
print(f"\nElements greater than 5: {arr[arr>5]}")

arr_copy = arr.copy()
arr_copy[arr_copy % 2 == 0] = 0
print(f"\nAfter replacing evens:\n{arr_copy}")
print(f"\nMean: {np.mean(arr,axis=0)}")



Second row:  [4 5 6]

Element in the third row, first column: 7

Elements greater than 5: [6 7 8 9]

After replacing evens:
[[1 0 3]
 [0 5 0]
 [7 0 9]]

Mean: [4. 5. 6.]


In [46]:
# Mathematical Operations: Create two arrays A = np.array([[1, 2], [3, 4]]) and B = np.array([[5, 6], [7, 8]]). Calculate:
# Element-wise multiplication
# Matrix multiplication
# Determinant of A
# Inverse of A
# Eigenvalues of A

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f"Element-wise multiplication: {A*B}")
print(f"\nMatrix multiplication: {A@B}")
print(f"\nDeterminant of A: {np.linalg.det(A):.2f}")
print(f"\nInverse of A: {np.linalg.inv(A)}")
print(f"\nEigenvalues of A: {np.linalg.eigvals(A)}")


Element-wise multiplication: [[ 5 12]
 [21 32]]

Matrix multiplication: [[19 22]
 [43 50]]

Determinant of A: -2.00

Inverse of A: [[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues of A: [-0.37228132  5.37228132]


In [49]:
# Broadcasting: Without using loops, perform:
# Subtract the mean of each column from its respective column in a 2D array
# Create a 5x5 array with row values ranging from 0 to 4
# Normalize each row of a 2D array to sum to 1
# Add a 1D array of length 3 to each row of a 4x3 array

# 1. Subtract column means
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
col_means = np.mean(data, axis=0)
centered_data = data - col_means
print(f"Centered data:\n{centered_data}")

# 2. 5x5 with row values 0-4
rows = np.arange(5)
grid = np.tile(rows, (5, 1))
print(f"\nGrid:\n{grid}")

# 3. Normalize rows to sum to 1
arr = np.random.randint(1, 10, size=(4, 3))
row_sums = np.sum(arr, axis=1, keepdims=True)
normalized = arr / row_sums
print(f"\nOriginal:\n{arr}")
print(f"\nRow sums: {np.sum(arr, axis=1)}")
print(f"\nNormalized:\n{normalized}")
print(f"\nNew row sums: {np.sum(normalized, axis=1)}")

# 4. Add 1D array to each row
matrix_4x3 = np.arange(12).reshape(4, 3)
vector = np.array([10, 20, 30])
result = matrix_4x3 + vector
print(f"\nMatrix:\n{matrix_4x3}")
print(f"\nVector: {vector}")
print(f"\nResult:\n{result}")


Centered data:
[[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]

Grid:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

Original:
[[2 5 7]
 [7 6 8]
 [2 3 9]
 [5 9 1]]

Row sums: [14 21 14 15]

Normalized:
[[0.14285714 0.35714286 0.5       ]
 [0.33333333 0.28571429 0.38095238]
 [0.14285714 0.21428571 0.64285714]
 [0.33333333 0.6        0.06666667]]

New row sums: [1. 1. 1. 1.]

Matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Vector: [10 20 30]

Result:
[[10 21 32]
 [13 24 35]
 [16 27 38]
 [19 30 41]]


In [50]:
# Data Analysis: You have temperature data for a week (7 days) from 3 different cities:

# Data: rows = cities, columns = days (Mon-Sun)
# temperatures = np.array([
#     [20, 22, 21, 23, 24, 22, 21],  # City A
#    [15, 16, 15, 17, 18, 16, 15],  # City B
#    [25, 26, 24, 27, 28, 26, 25]   # City C
#])
# Calculate:
# 1. The average temperature for each city
# 2. The hottest day across all cities (which day of week)
# 3. The city with the highest temperature variation
# 4. The number of days where City A was warmer than City B
# 5. Normalize the temperatures for each city to range [0, 1]

temperatures = np.array([
    [20, 22, 21, 23, 24, 22, 21],
    [15, 16, 15, 17, 18, 16, 15],
    [25, 26, 24, 27, 28, 26, 25]
])

days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

# 1. Average for each city
city_avg = np.mean(temperatures, axis=1)
for i, avg in enumerate(city_avg):
    print(f"City {chr(65+i)} average: {avg:.2f}°C")

#2. Hottest day overall
max_temp_idx = np.argmax(temperatures)
city_idx, day_idx = np.unravel_index(max_temp_idx, temperatures.shape)
print(f"\nHottest day: {days[day_idx]} in City {chr(65+city_idx)} at {temperatures[city_idx, day_idx]}°C")

# 3. City with highest variation (standard deviation)
city_std = np.std(temperatures, axis=1)
highest_var_city = np.argmax(city_std)
print(f"\nCity with highest variation: City {chr(65+highest_var_city)} (std: {city_std[highest_var_city]:.2f})")

# 4. Days where City A > City B
warmer_days = np.sum(temperatures[0] > temperatures[1])
print(f"\nCity A was warmer than City B on {warmer_days} days")

# 5. Normalize each city's temperatures to [0, 1]
city_min = np.min(temperatures, axis=1, keepdims=True)
city_max = np.max(temperatures, axis=1, keepdims=True)
normalized_temps = (temperatures - city_min) / (city_max - city_min)
print(f"Normalized temperatures:\n{normalized_temps}")


City A average: 21.86°C
City B average: 16.00°C
City C average: 25.86°C

Hottest day: Fri in City C at 28°C

City with highest variation: City A (std: 1.25)

City A was warmer than City B on 7 days
Normalized temperatures:
[[0.         0.5        0.25       0.75       1.         0.5
  0.25      ]
 [0.         0.33333333 0.         0.66666667 1.         0.33333333
  0.        ]
 [0.25       0.5        0.         0.75       1.         0.5
  0.25      ]]


In [51]:
#Boolean Masking: Given the array scores = np.array([[85, 92, 78], [90, 88, 95], [76, 82, 91], [88, 85, 79]])
#representing test scores (rows = students, columns = subjects), find:tudents who scored above 90 in any subject
#Subjects where average score is above 85
#Create a mask for scores between 80 and 90 (inclusive)
#Replace all scores below 80 with the subject's mean

scores = np.array([[85, 92, 78], [90, 88, 95], [76, 82, 91], [88, 85, 79]])

# 1. Students with any score > 90
any_above_90 = np.any(scores > 90, axis=1)
print(f"Students with any score > 90: {np.where(any_above_90)[0]}")

# 2. Subjects with average > 85
subject_avg = np.mean(scores, axis=0)
high_avg_subjects = np.where(subject_avg > 85)[0]
print(f"\nSubjects with avg > 85: {high_avg_subjects}")

# 3. Mask for scores 80-90
mask_80_90 = (scores >= 80) & (scores <= 90)
print(f"\nMask for scores 80-90:\n{mask_80_90}")

# 4. Replace scores < 80 with subject mean
scores_fixed = scores.copy()
subject_means = np.mean(scores, axis=0)
low_scores_mask = scores < 80
scores_fixed[low_scores_mask] = np.tile(subject_means, (scores.shape[0], 1))[low_scores_mask]
print(f"\nFixed scores:\n{scores_fixed}")


Students with any score > 90: [0 1 2]

Subjects with avg > 85: [1 2]

Mask for scores 80-90:
[[ True False False]
 [ True  True False]
 [False  True False]
 [ True  True False]]

Fixed scores:
[[85 92 85]
 [90 88 95]
 [84 82 91]
 [88 85 85]]


In [ ]:
                                                 #   ---------PRACTICE PROBLEMS--------   #

In [11]:
#Remove duplicates from List

#Using Set
print("Using Set")
num=[3, 2, 1, 2, 4, 3, 5, 1]
num1=set()
res=[]                           #stores elements in order
for item in num:
    if item not in num1:
        num1.add(item)
        res.append(item)
print(res)
print(num1)

#Using Dictionary
print("\nUsing Dictionary")
num=[3, 2, 1, 2, 4, 3, 5, 1]
res=list(dict.fromkeys(num))
print(res)

#Manual
print("\n Manual")
num=[3, 2, 1, 2, 4, 3, 5, 1]
res=[]
for i in num:
    if i not in res:
        res.append(i)
print(res)

Using Set
[3, 2, 1, 4, 5]
{1, 2, 3, 4, 5}

Using Dictionary
[3, 2, 1, 4, 5]

 Manual
[3, 2, 1, 4, 5]


In [22]:
#Find most frequent element

# Using counter
print("Using counter")
from collections import Counter
nums = [1, 3, 2, 3, 4, 3, 2, 1, 3]
count = Counter(nums)
element = count.most_common(1)[0][0]
print("Most common element:", element)

#Using Dictionary
print("\nUsing Dictionary")
nums = [1, 3, 2, 3, 4, 3, 2, 1, 3]
frequency={}
for i in nums:
    frequency[i]=frequency.get(i,0)+1
print("Most common element: ",max(frequency,key=frequency.get))

#Using max() and count()
print("\nUsing max() and count()")
nums = [1, 3, 2, 3, 4, 3, 2, 1, 3]
print("Most common element: ",max(set(nums), key=nums.count))

Using counter
Most common element: 3

Using Dictionary
Most common element:  3

Using max() and count()
Most common element:  3


In [26]:
#Check if Two Lists Have Common Elements

#Using Set Intersection
print("Using Set Intersection")
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 5]
print(set(list1)&set(list2))
print(bool(set(list1)&set(list2)))

#Using any()
print("\nUsing any()")
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 5]
set1=set(list2)
print(any(i in set1 for i in list1))

#Nested Loops
print("\nNested Loops")
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 5]  
common=False

for i in list1:
    for j in list2:
        if i==j:
            common=True
            break
    if common:
        break

print(common)
            

Using Set Intersection
{5}
True

Using any()
True

Nested Loops
True


In [5]:
#Flatten a Nested List

#Recursive
print("Recursive")
list1 = [1, [2, 3], [4, [5, 6]], 7]
res=[]

def flatten(lst):
    for i in lst:
        if type(i)==list:
            flatten(i)
        else:
            res.append(i)

flatten(list1)
print(res)

#Using Stack
print("\nUsing Stack")
list1 = [1, [2, 3], [4, [5, 6]], 7]
res=[]
stack=list1[::-1]

while stack:
    i=stack.pop()
    if type(i)==list:
        stack.extend(i[::-1])
    else:
        res.append(i)
print(res)

#Using List Comprehension with Recursion
print("\nUsing List Comprehension with Recursion")
list1 = [1, [2, 3], [4, [5, 6]], 7]

def flatten(lst):
    return [item for sublist in lst for item in (flatten(sublist) if type(sublist) == list else [sublist])]

print(flatten(list1))  


Recursive
[1, 2, 3, 4, 5, 6, 7]

Using Stack
[1, 2, 3, 4, 5, 6, 7]

Using List Comprehension with Recursion
[1, 2, 3, 4, 5, 6, 7]


In [7]:
#Group Anagrams

from collections import defaultdict

#Using Sorted String as Key
print("Using Sorted String as Key")

words = ["eat", "tea", "tan", "ate", "nat", "bat"]
anagram_groups = defaultdict(list)                    #Creates a dictionary

for word in words:
    sorted_word = ''.join(sorted(word))               #words with same letters get same sorted key
    anagram_groups[sorted_word].append(word)          #creates anagram

print(list(anagram_groups.values()))

#Using Character Count
print("\nUsing Character Count")

words = ["eat", "tea", "tan", "ate", "nat", "bat"]
anagram_groups = defaultdict(list)

for word in words:
    count = [0] * 26                                   #only lowercase 26 letters
    for char in word:
        count[ord(char) - ord('a')] += 1               #ord(char) → gives ASCII value
                                                       #ord('a') → ASCII of 'a'
    anagram_groups[tuple(count)].append(word)

print(list(anagram_groups.values()))

#Prime Multiplication
print("\nPrime Multiplication")

words = ["eat", "tea", "tan", "ate", "nat", "bat"]

primes = {
    'a': 2, 'b': 3, 'c': 5, 'd': 7, 'e': 11, 'f': 13, 'g': 17,
    'h': 19, 'i': 23, 'j': 29, 'k': 31, 'l': 37, 'm': 41, 'n': 43,
    'o': 47, 'p': 53, 'q': 59, 'r': 61, 's': 67, 't': 71, 'u': 73,
    'v': 79, 'w': 83, 'x': 89, 'y': 97, 'z': 101
}

anagram_groups = defaultdict(list)

for word in words:
    product = 1                               #multiply the prime numbers of each character
    for char in word:
        product *= primes[char]
    anagram_groups[product].append(word)

print(list(anagram_groups.values()))

Using Sorted String as Key
[['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]

Using Character Count
[['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]

Prime Multiplication
[['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]


In [12]:
#Find Intersection of Two Lists

list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]

#Set intersection
print("Set intersection")
intersect=list(set(list1) & set(list2))
print(intersect)

#List comprehension
print("\nList comprehension")
intersect=list(i for i in list1 if i in list2)
print(intersect)

#Using filter
print("\nUsing filter")
intersect=list(filter(lambda x: x in list1,list2))
print(intersect)

Set intersection
[4, 5]

List comprehension
[4, 5]

Using filter
[4, 5]


In [18]:
#Check if List is Palindrome

lst = [1, 2, 3, 2, 1]

#Slicing
print("Slicing")
print(lst==lst[::-1])

#Using reversed
print("\nUsing reversed")
print(lst==list(reversed(lst)))

#Two pointers
print("\nTwo pointers")
is_palindrome = True
left, right = 0, len(lst) - 1
while left < right:
    if lst[left] != lst[right]:
        is_palindrome = False
        break
    left += 1
    right -= 1
print(is_palindrome)  


Slicing
True

Using reversed
True

Two pointers
True


In [19]:
#Find Missing Number

nums = [1, 2, 4, 5, 6] 
n = 6

#Sum formula
print("Sum Formula")
expected_sum = n * (n + 1) // 2
actual_sum = sum(nums)
print(expected_sum - actual_sum)  

#Set difference
print("\n Set Difference")
full_set = set(range(1, n + 1))
print(list(full_set - set(nums))[0])  

#XOR
print("\nXOR")
xor_all = 0
xor_nums = 0
for i in range(1, n + 1):
    xor_all ^= i
for num in nums:
    xor_nums ^= num
print(xor_all ^ xor_nums)  


Sum Formula
3

 Set Difference
3

XOR
3


In [20]:
#Find First Non-Repeating Character

#Using OrderedDict
print("Using OrderedDict")
from collections import OrderedDict

text = "swiss"
char_count = OrderedDict()

for char in text:
    char_count[char] = char_count.get(char, 0) + 1

for char, count in char_count.items():
    if count == 1:
        print(f"First non-repeating: {char}")  
        break

#Using Counter and Loop
print("\nUsing Counter and Loop")
from collections import Counter

text = "swiss"
count = Counter(text)

for char in text:
    if count[char] == 1:
        print(f"First non-repeating: {char}")  
        break


#Manual Count
print("\nManual Count")
text = "swiss"
for i, char in enumerate(text):
    if text.count(char) == 1:
        print(f"First non-repeating: {char}")  
        break


Using OrderedDict
First non-repeating: w

Using Counter and Loop
First non-repeating: w

Manual Count
First non-repeating: w


In [23]:
#Check if Strings are Anagrams

#Sorting
print("Sorting")
s1 = "listen"
s2 = "silent"
print(sorted(s1)==sorted(s2))

#Character Count
print("\nCharacter Count")
s1 = "listen"
s2 = "silent"

if len(s1) != len(s2):
    print(False)
else:
    count = [0] * 26
    for char in s1:
        count[ord(char) - ord('a')] += 1
    for char in s2:
        count[ord(char) - ord('a')] -= 1
    print(all(c == 0 for c in count))  


# Using Counter
print("\nUsing Counter")
s1 = "listen"
s2 = "silent"
print(Counter(s1) == Counter(s2))  


Sorting
True

Character Count
True

Using Counter
True


In [24]:
#Find Duplicate Numbers

#: Using Set
print("Using Set")
nums = [1, 3, 4, 2, 2]
seen = set()
for num in nums:
    if num in seen:
        print(f"Duplicate: {num}")  
        break
    seen.add(num)

#Using Dictionary
print("\nUsing Dictionary")
nums = [1, 3, 4, 2, 2]
count = {}
for num in nums:
    if num in count:
        print(f"Duplicate: {num}") 
        break
    count[num] = 1

#Sorting
print("\nSorting")
nums = [1, 3, 4, 2, 2]
nums.sort()
for i in range(1, len(nums)):
    if nums[i] == nums[i-1]:
        print(f"Duplicate: {nums[i]}")  
        break

Using Set
Duplicate: 2

Using Dictionary
Duplicate: 2

Sorting
Duplicate: 2


In [26]:
#SET PROBLEMS

#Find common elements in three lists

list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
list3 = [5, 6, 7, 8, 9]
common=set(list1)&set(list2)&set(list3)
print(common)


{5}


In [28]:
#Find unique characters in string

word = "hello world"
unique=set(word.replace(" ",""))
print(unique)

{'e', 'l', 'h', 'o', 'r', 'w', 'd'}


In [30]:
#Check if two strings are permutations

str1 = "listen"
str2 = "silent"
print(set(str1)==set(str2) and len(str1)==len(str2))

True
